type Meetup {
  id: ID!
  rsvps: RSVPConnection
}

type RSVPConnection {
  count: Number!
  items: [RSCP]!
}

type RSVP {
  id: ID!
  name: String!
}

type Query {
  allMeetups: [Meetup!] @index(name: "all_meetups")
}

type Mutation {
  rsvp(meetupId: ID!, name: String!): Meetup! @resolver(name: "rsvp")
}
